name: Stancer test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv 
        uses: astral-sh/setup-uv@v5
        with:
            version: "0.7.14"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync

      - name: Build the project
        run: python -m build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
            name: dist-artifact
            path: dist/ 